title = "Web-Crawler config"

[Downloader]
seed_urls = ["http://odp.org/"]
query_delay = 5000 # milliseconds

[Spider]
num_threads = 1

[Database]
db_name = "/app/data/links" #"/app/data/links"
table_name = "urls"
ids_row_name = "id"
urls_row_name = "url" 